---
name: Primeros programas en Q1
locale: es
type: learning
beta: false
teacher_info: ''
language: qsim
id_format: '%05d'
order:
- 5
- 1
- 2
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 3
- 13
- 4
- 14
- 16
- 15
- 17
- 18
- 19
- 20
- 21
